---
- name: Remove docker and docker-runc
  zypper:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-runc
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: Install docker
  command: "zypper install -y --force-resolution --replacefiles {{ docker_version_map[docker_version]['package'] }}"
  args:
    warn: false
