---
- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- include_tasks: install_dependencies.yml
- ansible.builtin.include_tasks: install_podman.yml
  tags: [install_podman, destructive]
  when: container_engine == "Podman"
