---
- name: Remove docker
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: Add Docker GPG Key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add docker repository
  yum_repository:
    name: "{{ docker_version_map[docker_version]['name'] }}"
    description: "Docker repository"
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    enabled: yes
    gpgcheck: no
  register: repo_installed
  retries: 10
  delay: 30
  until: repo_installed is success

- name: Install docker
  package:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    state: present