---
- name: Modify GRUB_CMDLINE_LINUX
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=\"[^\"]*)(\".*)'
    line: '\1 cgroup_enable=memory swapaccount=1 cgroup.memory=nokmem\2'
  when: is_nokmem_present.rc == 1

- name: Run bootloader update
  command: "{{ bootloader_update_command }}"
