---
# Note: this code is largely copied from the RedHat-8 version

# - name: Remove Podman
#   package:
#     name: "{{ packages }}"
#     state: absent
#   vars:
#     packages:
#     - docker
#     - podman
#   register: remove_packages
#   retries: 10
#   delay: 30
#   until: remove_packages is success

- name: disable SELinux
  selinux:
    state: disabled

- name: Install Podman
  package:
    name: "{{ podman_version_map[podman_version]['package'] }}"
    state: present
  loop:
    - "{{ podman_version_map[podman_version]['package'] }}"

- name: Verify that fs.may_detach_mounts is enabled
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.may_detach_mounts'
    line: 'fs.may_detach_mounts = 1'
    create: yes
