---
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/base/general/manage_firewalld.yml"

- ansible.builtin.include_tasks: install_dependencies.yml
- ansible.builtin.include_tasks: install_podman.yml
  tags: [install_podman, install_docker, destructive]
  when: container_engine == "Podman"

- ansible.builtin.include_tasks: configure_cni_network.yml
  tags: [install_podman, install_docker, destructive]
  when: container_engine == "Podman"

- ansible.builtin.include_tasks: install_docker.yml
  tags: [install_docker, destructive]
  when: container_engine == "Docker"


