---
- name: Make sure /mnt/data exists
  file:
    path: /mnt/data
    state: directory

- name: Create the volume
  lvg:
    vg: lxc
    pvs: /dev/{{ device_name }}
    force: true

- name: Define size of swap
  shell: SWAP_MAX_SIZE=$(sudo vgdisplay --units M lxc | grep "VG Size" | awk '{ print mem=int(0.07*$3) }'); grep MemTotal /proc/meminfo | awk -v MAXMEM=${SWAP_MAX_SIZE} '{ mem=int($2/(2*1024)); if(mem>MAXMEM) mem=MAXMEM; print mem; }'
  register: swap_size

- name: Create swap volume
  lvol:
    vg: lxc
    lv: swap
    size: "{{swap_size.stdout}}m"
    force: true

- name: Create data volume
  lvol:
    vg: lxc
    lv: data
    size: 100%FREE
    force: true

- name: Setup swap
  command: mkswap /dev/lxc/swap

- name: Create xfs filesystem on /dev/lxc/data
  filesystem:
    fstype: xfs
    dev: /dev/lxc/data

- name: remove automount of /dev/{{ device_name }}
  lineinfile:
    path:  /etc/fstab
    state: absent
    regexp: '^/dev/{{ device_name }}'

- name: Add entries to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
  with_items:
    - '/dev/lxc/swap swap       swap  swap  0 0'
    - '/dev/lxc/data /mnt/data  xfs   defaults,pquota,prjquota,x-systemd.automount  0 0'

- name: Mount /dev/lxc/data
  command: mount /dev/lxc/data

- name: Enable all swap devices
  command: swapon -a
  args:
    warn: false
