---
# As per the doc
# https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
- name: Remove docker
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success
- name: Add docker repository key
  apt_key:
    url: "{{ docker_version_map[docker_version]['keys']['server'] }}"
    id: "{{ docker_version_map[docker_version]['keys']['id'] }}"

- name: Add docker repository
  apt_repository:
    repo: "{{ docker_version_map[docker_version]['repo'] }}"
    state: present

- name: Install docker
  apt:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    update_cache: yes
    state: present

- name: Pin docker-engine packet
  shell: echo "docker-engine hold" | sudo dpkg --set-selections
